
package introsde.document.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://ws.document.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonListResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonListRequest", output = "http://ws.document.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.CreatePersonResponse")
    @Action(input = "http://ws.document.introsde/People/createPersonRequest", output = "http://ws.document.introsde/People/createPersonResponse")
    public void createPerson(
        @WebParam(name = "person", targetNamespace = "http://ws.document.introsde/", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.document.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "http://ws.document.introsde/")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonRequest", output = "http://ws.document.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePersonResponse")
    @Action(input = "http://ws.document.introsde/People/updatePersonRequest", output = "http://ws.document.introsde/People/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "http://ws.document.introsde/", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "delete", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.DeletePersonResponse")
    @Action(input = "http://ws.document.introsde/People/deletePersonRequest", output = "http://ws.document.introsde/People/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @param type
     * @return
     *     returns java.util.List<introsde.document.ws.Measure>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonHistoryResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonHistoryRequest", output = "http://ws.document.introsde/People/readPersonHistoryResponse")
    public List<Measure> readPersonHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.ws.Measure>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadMeasureTypesResponse")
    @Action(input = "http://ws.document.introsde/People/readMeasureTypesRequest", output = "http://ws.document.introsde/People/readMeasureTypesResponse")
    public List<Measure> readMeasureTypes();

    /**
     * 
     * @param personId
     * @param type
     * @param idMeasure
     * @return
     *     returns introsde.document.ws.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonMeasureResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonMeasureRequest", output = "http://ws.document.introsde/People/readPersonMeasureResponse")
    public Measure readPersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "idMeasure", targetNamespace = "")
        int idMeasure);

    /**
     * 
     * @param measure
     * @param personId
     * @throws ParseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.document.introsde/People/savePersonMeasureRequest", output = "http://ws.document.introsde/People/savePersonMeasureResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://ws.document.introsde/People/savePersonMeasure/Fault/ParseException")
    })
    public void savePersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measure", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Measure> measure)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param measure
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePersonMeasureResponse")
    @Action(input = "http://ws.document.introsde/People/updatePersonMeasureRequest", output = "http://ws.document.introsde/People/updatePersonMeasureResponse")
    public void updatePersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measure", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Measure> measure);

    /**
     * 
     * @param personId
     * @param type
     * @return
     *     returns java.util.List<introsde.document.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readPersonGoalHistory", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonGoalHistory")
    @ResponseWrapper(localName = "readPersonGoalHistoryResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonGoalHistoryResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonGoalHistoryRequest", output = "http://ws.document.introsde/People/readPersonGoalHistoryResponse")
    public List<Goal> readPersonGoalHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoalTypes", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoalTypes")
    @ResponseWrapper(localName = "readGoalTypesResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoalTypesResponse")
    @Action(input = "http://ws.document.introsde/People/readGoalTypesRequest", output = "http://ws.document.introsde/People/readGoalTypesResponse")
    public List<Goal> readGoalTypes();

    /**
     * 
     * @param idGoal
     * @param personId
     * @param type
     * @return
     *     returns introsde.document.ws.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readPersonGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonGoal")
    @ResponseWrapper(localName = "readPersonGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadPersonGoalResponse")
    @Action(input = "http://ws.document.introsde/People/readPersonGoalRequest", output = "http://ws.document.introsde/People/readPersonGoalResponse")
    public Goal readPersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "idGoal", targetNamespace = "")
        int idGoal);

    /**
     * 
     * @param goal
     * @param personId
     * @throws ParseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.SavePersonGoal")
    @ResponseWrapper(localName = "savePersonGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.SavePersonGoalResponse")
    @Action(input = "http://ws.document.introsde/People/savePersonGoalRequest", output = "http://ws.document.introsde/People/savePersonGoalResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://ws.document.introsde/People/savePersonGoal/Fault/ParseException")
    })
    public void savePersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "goal", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Goal> goal)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param goal
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "updatePersonGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePersonGoal")
    @ResponseWrapper(localName = "updatePersonGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdatePersonGoalResponse")
    @Action(input = "http://ws.document.introsde/People/updatePersonGoalRequest", output = "http://ws.document.introsde/People/updatePersonGoalResponse")
    public void updatePersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "goal", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Goal> goal);

}
